### ISSUE TITLE
Setting values like timer, or picture mode?

### ISSUE THREAD

**Issue by erodewald** [heathbar/vizio-smart-cast#12]
Hi, 

Great library, thanks. Working on a little SmartThings Automation to automate some basic "sleep time" functions when my lights turn off, but I can't figure out how to _set_ the TV's current picture mode, or the sleep timer. Is it impossible with Vizio's current API?

Thanks.

**Comment by heathbar** [comment]
Does the tv.settings.picture.get() method not return the picture info?

**Comment by heathbar** [comment]
Correct, the interface is not RESTful. But you have the info there. I see a field named VALUE which is currently "Calibrated". So that's the picture mode you have set, right? The ELEMENTS array holds all possible values that you can set it to which is the standard modes, plus a couple it looks like you've created named "best" and "superdark".

As far as setting the values, it looks like I didn't write that part yet. 🙄 Sorry.

**Comment by erodewald** [comment]
Great, you're confirming my hopes that their API is totally capable of it! No apologies necessary. If it's not on your radar, I'd consider doing the legwork and submitting a PR.

**Comment by heathbar** [comment]
That would be amazing.

**Comment by heathbar** [comment]
Have a look at how volume is currently set (line 196 in iindex.js). You'll probably have to do something similar to that: query the value, then use the HASHVAL from the query in the PUT request.

**Comment by erodewald** [comment]
Thanks @heathbar - I'll familiarize myself with it soon. I sent you an email regarding other matters, by the way.

**Comment by heathbar** [comment]
Closed by #13
